// Code generated by protoc-gen-go. DO NOT EDIT.
// source: custshopsvc.proto

package protofiles

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Jsondata             []byte   `protobuf:"bytes,1,opt,name=jsondata,proto3" json:"jsondata,omitempty"`
	ModelType            string   `protobuf:"bytes,2,opt,name=modelType,proto3" json:"modelType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetJsondata() []byte {
	if m != nil {
		return m.Jsondata
	}
	return nil
}

func (m *CreateRequest) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

type UpdateRequest struct {
	Jsondata             []byte   `protobuf:"bytes,1,opt,name=jsondata,proto3" json:"jsondata,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ModelType            string   `protobuf:"bytes,3,opt,name=modelType,proto3" json:"modelType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{1}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetJsondata() []byte {
	if m != nil {
		return m.Jsondata
	}
	return nil
}

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelType            string   `protobuf:"bytes,2,opt,name=modelType,proto3" json:"modelType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{2}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteRequest) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

type GetByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	ModelType            string   `protobuf:"bytes,3,opt,name=modelType,proto3" json:"modelType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDRequest) Reset()         { *m = GetByIDRequest{} }
func (m *GetByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIDRequest) ProtoMessage()    {}
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{3}
}

func (m *GetByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDRequest.Unmarshal(m, b)
}
func (m *GetByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDRequest.Merge(m, src)
}
func (m *GetByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIDRequest.Size(m)
}
func (m *GetByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDRequest proto.InternalMessageInfo

func (m *GetByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetByIDRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *GetByIDRequest) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

type GetByParametersRequest struct {
	SearchParam          string   `protobuf:"bytes,1,opt,name=searchParam,proto3" json:"searchParam,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	ModelType            string   `protobuf:"bytes,3,opt,name=modelType,proto3" json:"modelType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByParametersRequest) Reset()         { *m = GetByParametersRequest{} }
func (m *GetByParametersRequest) String() string { return proto.CompactTextString(m) }
func (*GetByParametersRequest) ProtoMessage()    {}
func (*GetByParametersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{4}
}

func (m *GetByParametersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByParametersRequest.Unmarshal(m, b)
}
func (m *GetByParametersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByParametersRequest.Marshal(b, m, deterministic)
}
func (m *GetByParametersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByParametersRequest.Merge(m, src)
}
func (m *GetByParametersRequest) XXX_Size() int {
	return xxx_messageInfo_GetByParametersRequest.Size(m)
}
func (m *GetByParametersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByParametersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByParametersRequest proto.InternalMessageInfo

func (m *GetByParametersRequest) GetSearchParam() string {
	if m != nil {
		return m.SearchParam
	}
	return ""
}

func (m *GetByParametersRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *GetByParametersRequest) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

type CreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ErrorResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{6}
}

func (m *ErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorResponse.Unmarshal(m, b)
}
func (m *ErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorResponse.Marshal(b, m, deterministic)
}
func (m *ErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorResponse.Merge(m, src)
}
func (m *ErrorResponse) XXX_Size() int {
	return xxx_messageInfo_ErrorResponse.Size(m)
}
func (m *ErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorResponse proto.InternalMessageInfo

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ModelResponse struct {
	Jsondata             []byte   `protobuf:"bytes,1,opt,name=jsondata,proto3" json:"jsondata,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModelResponse) Reset()         { *m = ModelResponse{} }
func (m *ModelResponse) String() string { return proto.CompactTextString(m) }
func (*ModelResponse) ProtoMessage()    {}
func (*ModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bec96e7188cbb94, []int{7}
}

func (m *ModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModelResponse.Unmarshal(m, b)
}
func (m *ModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModelResponse.Marshal(b, m, deterministic)
}
func (m *ModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModelResponse.Merge(m, src)
}
func (m *ModelResponse) XXX_Size() int {
	return xxx_messageInfo_ModelResponse.Size(m)
}
func (m *ModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModelResponse proto.InternalMessageInfo

func (m *ModelResponse) GetJsondata() []byte {
	if m != nil {
		return m.Jsondata
	}
	return nil
}

func (m *ModelResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "protofiles.CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "protofiles.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "protofiles.DeleteRequest")
	proto.RegisterType((*GetByIDRequest)(nil), "protofiles.GetByIDRequest")
	proto.RegisterType((*GetByParametersRequest)(nil), "protofiles.GetByParametersRequest")
	proto.RegisterType((*CreateResponse)(nil), "protofiles.CreateResponse")
	proto.RegisterType((*ErrorResponse)(nil), "protofiles.ErrorResponse")
	proto.RegisterType((*ModelResponse)(nil), "protofiles.ModelResponse")
}

func init() {
	proto.RegisterFile("custshopsvc.proto", fileDescriptor_1bec96e7188cbb94)
}

var fileDescriptor_1bec96e7188cbb94 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0x80, 0x19, 0x44, 0x23, 0x4f, 0x07, 0xb1, 0x31, 0x06, 0x17, 0x0f, 0xa4, 0x89, 0x09, 0x27,
	0x0e, 0x9a, 0x78, 0xf3, 0xa0, 0x60, 0x90, 0x83, 0x89, 0x19, 0x78, 0xf0, 0x58, 0xb7, 0x47, 0x98,
	0x19, 0xb4, 0xb6, 0x85, 0x84, 0xff, 0xe0, 0x8f, 0x36, 0x6c, 0x74, 0x50, 0xa8, 0x68, 0x3c, 0x41,
	0xfb, 0xde, 0xfb, 0xde, 0x7b, 0xeb, 0x07, 0xa7, 0xd1, 0x4c, 0x69, 0x35, 0xe6, 0x42, 0xcd, 0xa3,
	0xb6, 0x90, 0x5c, 0x73, 0x02, 0xd9, 0xcf, 0x28, 0x49, 0x51, 0xd1, 0x3e, 0xf8, 0x1d, 0x89, 0x4c,
	0x63, 0x88, 0x9f, 0x33, 0x54, 0x9a, 0x04, 0x70, 0xf4, 0xa1, 0xf8, 0x34, 0x66, 0x9a, 0x35, 0xbc,
	0xa6, 0xd7, 0x3a, 0x09, 0x8b, 0x33, 0xb9, 0x84, 0xea, 0x84, 0xc7, 0x98, 0x0e, 0x17, 0x02, 0x1b,
	0xe5, 0xa6, 0xd7, 0xaa, 0x86, 0xeb, 0x0b, 0xfa, 0x06, 0xfe, 0xab, 0x88, 0xff, 0x88, 0xaa, 0x41,
	0x39, 0x89, 0x57, 0x8c, 0x72, 0x12, 0xdb, 0xe8, 0xca, 0x36, 0xfa, 0x0e, 0xfc, 0x2e, 0xa6, 0xb8,
	0x46, 0xe7, 0xe5, 0x9e, 0xbb, 0x7c, 0x67, 0xb2, 0x21, 0xd4, 0x7a, 0xa8, 0x1f, 0x16, 0xfd, 0xee,
	0x4f, 0xf5, 0x67, 0x70, 0x30, 0x4a, 0x30, 0x35, 0x13, 0xe5, 0x87, 0x5f, 0x86, 0x9a, 0xc2, 0x79,
	0x46, 0x7d, 0x61, 0x92, 0x4d, 0x50, 0xa3, 0x54, 0x86, 0xde, 0x84, 0x63, 0x85, 0x4c, 0x46, 0xe3,
	0x2c, 0xb4, 0x6a, 0xb3, 0x79, 0xf5, 0xaf, 0x7e, 0xb7, 0x50, 0x33, 0x4f, 0xa5, 0x04, 0x9f, 0x2a,
	0x74, 0x6d, 0x81, 0x52, 0x72, 0x69, 0xa8, 0xd9, 0x81, 0x5e, 0x81, 0xff, 0xb8, 0xfc, 0x53, 0x94,
	0x15, 0x69, 0xde, 0x66, 0xda, 0x3d, 0xf8, 0xcf, 0xcb, 0x5e, 0x45, 0xda, 0xbe, 0xe7, 0x73, 0x76,
	0xba, 0xfe, 0xaa, 0x40, 0xbd, 0x33, 0x53, 0x7a, 0x30, 0xe6, 0x62, 0x80, 0x72, 0x9e, 0x44, 0x48,
	0x9e, 0x8c, 0x60, 0xe6, 0xe2, 0xa2, 0xbd, 0xd6, 0xaf, 0x6d, 0xb9, 0x17, 0x04, 0xae, 0x50, 0x3e,
	0x0d, 0x2d, 0x91, 0x9e, 0xf1, 0xcb, 0x49, 0xb2, 0xd4, 0x0b, 0xac, 0x90, 0xb5, 0x7d, 0x0e, 0xca,
	0x6d, 0x72, 0x82, 0x2c, 0xd1, 0xf6, 0x83, 0xfa, 0x85, 0x57, 0x86, 0x64, 0x6d, 0x60, 0x3b, 0x67,
	0xa3, 0xac, 0x4f, 0x4d, 0x4b, 0x24, 0x84, 0xfa, 0x96, 0x4c, 0x84, 0xee, 0xb0, 0x76, 0x4c, 0xdb,
	0xcb, 0x7c, 0x3f, 0xcc, 0x62, 0x37, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x67, 0x4c, 0x93, 0x10,
	0x03, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CustShopServiceClient is the client API for CustShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustShopServiceClient interface {
	CreateService(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	UpdateService(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	DeleteService(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
	GetByIDService(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*ModelResponse, error)
	GetByParameters(ctx context.Context, in *GetByParametersRequest, opts ...grpc.CallOption) (*ModelResponse, error)
}

type custShopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustShopServiceClient(cc grpc.ClientConnInterface) CustShopServiceClient {
	return &custShopServiceClient{cc}
}

func (c *custShopServiceClient) CreateService(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/protofiles.CustShopService/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custShopServiceClient) UpdateService(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/protofiles.CustShopService/UpdateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custShopServiceClient) DeleteService(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, "/protofiles.CustShopService/DeleteService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custShopServiceClient) GetByIDService(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*ModelResponse, error) {
	out := new(ModelResponse)
	err := c.cc.Invoke(ctx, "/protofiles.CustShopService/GetByIDService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *custShopServiceClient) GetByParameters(ctx context.Context, in *GetByParametersRequest, opts ...grpc.CallOption) (*ModelResponse, error) {
	out := new(ModelResponse)
	err := c.cc.Invoke(ctx, "/protofiles.CustShopService/GetByParameters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustShopServiceServer is the server API for CustShopService service.
type CustShopServiceServer interface {
	CreateService(context.Context, *CreateRequest) (*CreateResponse, error)
	UpdateService(context.Context, *UpdateRequest) (*ErrorResponse, error)
	DeleteService(context.Context, *DeleteRequest) (*ErrorResponse, error)
	GetByIDService(context.Context, *GetByIDRequest) (*ModelResponse, error)
	GetByParameters(context.Context, *GetByParametersRequest) (*ModelResponse, error)
}

// UnimplementedCustShopServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCustShopServiceServer struct {
}

func (*UnimplementedCustShopServiceServer) CreateService(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (*UnimplementedCustShopServiceServer) UpdateService(ctx context.Context, req *UpdateRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (*UnimplementedCustShopServiceServer) DeleteService(ctx context.Context, req *DeleteRequest) (*ErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteService not implemented")
}
func (*UnimplementedCustShopServiceServer) GetByIDService(ctx context.Context, req *GetByIDRequest) (*ModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIDService not implemented")
}
func (*UnimplementedCustShopServiceServer) GetByParameters(ctx context.Context, req *GetByParametersRequest) (*ModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByParameters not implemented")
}

func RegisterCustShopServiceServer(s *grpc.Server, srv CustShopServiceServer) {
	s.RegisterService(&_CustShopService_serviceDesc, srv)
}

func _CustShopService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustShopServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.CustShopService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustShopServiceServer).CreateService(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustShopService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustShopServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.CustShopService/UpdateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustShopServiceServer).UpdateService(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustShopService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustShopServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.CustShopService/DeleteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustShopServiceServer).DeleteService(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustShopService_GetByIDService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustShopServiceServer).GetByIDService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.CustShopService/GetByIDService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustShopServiceServer).GetByIDService(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustShopService_GetByParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustShopServiceServer).GetByParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protofiles.CustShopService/GetByParameters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustShopServiceServer).GetByParameters(ctx, req.(*GetByParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustShopService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protofiles.CustShopService",
	HandlerType: (*CustShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateService",
			Handler:    _CustShopService_CreateService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _CustShopService_UpdateService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _CustShopService_DeleteService_Handler,
		},
		{
			MethodName: "GetByIDService",
			Handler:    _CustShopService_GetByIDService_Handler,
		},
		{
			MethodName: "GetByParameters",
			Handler:    _CustShopService_GetByParameters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "custshopsvc.proto",
}
